name: Build Javascript
on:
  workflow_call:
    inputs:
      env:
        description: environment to deploy
        required: true
        type: string
    secrets:
      PACKAGES_ACCESS:
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          scope: '@p00ls'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_ACCESS }}
      - name: Build
        run: |
          if [ "${{ inputs.env }}" = "devel" ]; then
            yarn build:staging
          elif [ "${{ inputs.env }}" = "prod" ]; then
            yarn build:production
          else
            yarn build
          fi 
