name: ci

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          cache: 'yarn'
          scope: '@p00ls'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable --immutable-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build artifact
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            yarn build:staging
          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
            yarn build:production
          else
            yarn build
          fi 
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy_preview:
    needs: [ build ]
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/cd.yml
    with:
      project_id: prj-zzf-p-dex-846e
      target: p00ls-dex-info-devel
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRJ_ZZF_P_DEX_846E }}
      repo_token: '${{ secrets.GITHUB_TOKEN }}'

  deploy_prod:
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd.yml
    with:
      channel_id: live
      project_id: prj-zzf-p-dex-846e
      target: p00ls-dex-info-devel
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRJ_ZZF_P_DEX_846E }}
      repo_token: '${{ secrets.GITHUB_TOKEN }}'