name: datadog

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed
  pull_request:
    types:
      - opened
      - closed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/datadog-actions-metrics@v1.20.0
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY_FOR_CI_METRICS }}
          collect-job-metrics: ${{ github.event.workflow_run.head_branch == github.event.repository.default_branch || github.event.workflow_run.head_branch == 'main' }}
