name: Deploy env to bucket
on:
  workflow_call:
    inputs:
      env:
        description: environment to deploy
        required: true
        type: string
      ref:
        description: SHA1 to checkout
        required: false
        default: 'latest'
        type: string
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      INFO_GCLOUD_SA:
        required: true
      BUCKET_NAME:
        required: true
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      COMMIT_ID: ${{ inputs.ref == 'latest' && github.sha || inputs.ref }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_ID }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          scope: '@p00ls'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_ACCESS }}
      - name: Build
        run: |
          if [ "${{ inputs.env }}" = "devel" ]; then
            yarn build:staging
          elif [ "${{ inputs.env }}" = "prod" ]; then
            yarn build:production
          else
            yarn build
          fi
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.INFO_GCLOUD_SA }}
      - name: Deploy
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'build'
          destination: ${{ secrets.BUCKET_NAME }}
          parent: false
